Repository gtech-mulearn/IEEE-LAUNCHPAD, pull requests merged in 2024-06, with the labels that each got.

#429 Create meenakshys-2@mulearn.md
  profiles/meenakshys-2@mulearn.md
Labels: Approved

#430 Create mohammedzohil@mulearn
  profiles/mohammedzohil@mulearn.md
Labels: Approved

#437 Create mariasararaju@mulearn.md
  profiles/mariasararaju@mulearn.md
Labels: Approved

#438 Create rahulpr-1@mulearn.md
  profiles/rahulpr-1@mulearn.md
Labels: Approved

#435 arjunv-7@mulearn
  profiles/arjunv-7@mulearn.md
Labels: Approved

#434 Create smithinthankachan-1@mulearn.md
  profiles/smithinthankachan-1@mulearn.md
Labels: Approved

#439 drijusha.t.k@mulearn.md
  drijusha.t.k@mulearn.md
Labels: Approved

#441 Create minhajvshams@mulearn.md
  profiles/minhajvshams@mulearn.md
Labels: Approved

#442 Create nadhanajeebkc@mulearn.md
  profiles/nadhanajeebkc@mulearn.md
Labels: Approved

#443 josepaul-2@mulearn
  profiles/josepaul-2@mulearn.md
Labels: Approved

#453 Create amalnakharish@mulearn.md
  profiles/amalnakharish@mulearn.md
Labels: Approved

#450 Create nivyac@mulearn.md
  profiles/nivyac@mulearn.md
Labels: documentation, Approved

#454 anaswarac@mulearn.md
  profiles/anaswarac@mulearn.md
Labels: Approved

#459 Create krishnapm@mulearn.md
  profiles/krishnapm@mulearn.md
Labels: Approved

#461 aryakp-1@mulearn.md
  profiles/aryakp-1@mulearn.md
Labels: Approved

#463 rakeshnarayanancn@mulearn
  profiles/rakeshnarayanancn@mulearn.md
Labels: Approved

#464 ashnaa@mulearn
  profiles/ashnaa@mulearn.md
Labels: Approved

#469 Create rainahenry@mulearn.md
  profiles/rainahenry@mulearn.md
Labels: Approved

#470 adding abhisheks-14@mulearn.md
  profiles/abhisheks-14@mulearn.md
Labels: Approved

#472 Organized muzammilibrahim@mulearn.md titles
  profiles/muzammilibrahim@mulearn.md
Labels: Approved

#473 ajithabhkrishna-1@mulearn.md
  profiles/ajithabhkrishna-1@mulearn.md
Labels: Approved

#474 Create niyathimariyageorge-1@mulearn.md
  profiles/niyathimariyageorge-1@mulearn.md
Labels: Approved

#475 Create ashermathewskoshy@mulearn.md
  profiles/ashermathewskoshy@mulearn.md
Labels: Approved

#477 Create smritisrinivas-1@mulearn.md
  profiles/smritisrinivas-1@mulearn.md
Labels: Approved

#478 Create antonypb@mulearn.md
  profiles/antonypb@mulearn.md
Labels: Approved

#480 anjalirajendran@mulearn
  profiles/anjalirajendran@mulearn.md
Labels: Approved

#484 Create sruthina@mulearn.md
  profiles/sruthina@mulearn.md
Labels: Approved

#481 sameemulhaquek@mulearn
  profiles/sameemulhaquek@mulearn.md
Labels: Approved

#485 profile changed
  profiles/syamkrishnankk@mulearn.md
Labels: Approved

#486 johaanpauljoe@mulearn
  profiles/johaanpauljoe@mulearn.md
Labels: Approved

#490 Create vyshnavkk@mulearn.md
  profiles/vyshnavkk@mulearn.md
Labels: Approved

#492 Create gauthamkrishnap@mulearn.md
  profiles/gauthamkrishnap@mulearn.md
Labels: Approved

#493 Create johnpiusthayiparampil@mulearn.md
  profiles/johnpius@mulearn.md
  profiles/johnpiusthayiparampil@mulearn.md
Labels: Approved

#495 fayizamp@mulearn
  profiles/fayizamp@mulearn.md
Labels: Approved

#498 created profile
  profiles/anumodtpramod@mulearn.md
Labels: Approved

#499 Create suryap@mulearn.md
  suryap@mulearn.md
Labels: Approved

#500 deekshithadinesh@mulearn
  profiles/deekshithadinesh@mulearn.md
Labels: Approved

#501 savanthp.s@mulearn
  profiles/savanthp.s@mulearn.md
Labels: Approved

#502 Create leyanarathfrancisp@mulearn.md
  profiles/leyanarathfrancisp@mulearn.md
Labels: Approved

#503 Create malavikaskumar@mulearn.md
  profiles/malavikaskumar@mulearn.md
Labels: Approved

#458 ajayvishnue@mulearn
  profiles/ajayvishnue@mulearn.md
Labels: Changes Requested

#505 Create yadhukrishnak@mulearn.md
  profiles/yadhukrishnak@mulearn.md
Labels: Approved

#510 Create milenninanittyeipe@mulearn.md
  profiles/milenninanittyeipe@mulearn.md
Labels: Approved

#511 Create ghanasyamvj@mulearn.md
  profiles/ghanasyamvj@mulearn.md
Labels: Approved

#513 Add suryap@mulearn.md
  profiles/suryap@mulearn.md
Labels: Approved

#523 Create anaswarap-2@mulearn.md
  profiles/anaswarap-2@mulearn.md
Labels: Approved

#526 Create govindk@mulearn.md
  profiles/govindk@mulearn.md
Labels: Approved

#529 Create adithyaar@mulearn.md
  profiles/adithyaar@mulearn.md
Labels: Approved

#538 Create gijogeorgep@mulearn.md
  profiles/gijogeorgep@mulearn.md
Labels: Approved

#540 Create ragini@mulearn.md
  profiles/ragini@mulearn.md
Labels: Approved

#543 ericbinukoshy@mulearn.md
  profiles/ericbinukoshy@mulearn.md
Labels: Approved

#544 Portfolio
  profiles/devarajr@mulearn.md
Labels: Approved

#545 Create amithamadhavcs@mulearn.md
  profiles/amithamadhavcs@mulearn.md
Labels: Approved

#546 Create mrudhulauk@mulearn.md
  profiles/mrudhulauk@mulearn.md
Labels: Approved

#548 naeemaziyad@mulearn
  profiles/naeemaziyad@mulearn.md
Labels: Approved

#550 leanamerinison@mulearn
  profiles/leanamerinison@mulearn.md
Labels: Approved

#556 Create basilashrafn@mulearn.md
  profiles/basilashrafn@mulearn.md
Labels: Approved

#559 anugrahp@mulearn
  profiles/anugrahp@mulearn.md
Labels: Approved

#561 Create muhammedsheffinkhanpa@mulearn.md
  profiles/muhammedsheffinkhanpa@mulearn.md
Labels: Approved

#560 Create arfinnassar@mulearn.md
  profiles/arfinnassar@mulearn.md
Labels: Approved

#562 Update anusreekv@mulearn.md
  profiles/anusreekv@mulearn.md
Labels: Approved

#565 Athira J K
  profiles/athirajk@mulearn.md
Labels: Approved

#568 Create jeevanvarghese@mulearn.md
  profiles/jeevanvarghese@mulearn.md
Labels: Approved

#575 Revert "Create mohammedhaneefez@mulearn.md"
  mohammedhaneefez@mulearn.md
Labels: Changes Requested

#578 abijiths-1@mulearn.md
  profiles/abijiths-1@mulearn.md
Labels: Approved

#589 Create amelshab@mulearn.md
  profiles/amelshab@mulearn.md
Labels: Approved

#592 Create ramsifavaskp@mulearn.md
  profiles/ramsifavaskp@mulearn.md
Labels: Approved

#594 Create navaneethvnair@mulearn.md
  profiles/navaneethvnair@mulearn.md
Labels: Approved

#597 Create adithyanv-2@mulearn.md
  profiles/adithyanv-2@mulearn.md
Labels: Approved

#598 Update adithyanv-2@mulearn.md
  profiles/adithyanv-2@mulearn.md
Labels: Approved

#602 Create nidhinmohan@mulearn.md
  profiles/nidhinmohan@mulearn.md
Labels: Approved

#604 Create ayas@mulearn.md
  profiles/ayas@mulearn.md
Labels: Approved

#613 Create riyanps@mulearn.md
  profiles/riyanps@mulearn.md
Labels: Approved

#614 Create aaronb@mulearn.md
  profiles/aaronb@mulearn.md
Labels: Approved

#618 angelrosetj@mulearn
  profiles/angelrosetj@mulearn.md
Labels: Approved

#631 meghaanil@mulearn.md
  profiles/meghaanil@mulearn.md
Labels: Approved

#638 sssneha@mulearn.md
  profiles/snehass@mulearn.md
Labels: Approved

#642 Create sreelakshmis@mulearn.md
  profiles/sreelakshmis@mulearn.md
Labels: Approved

#645 Create nayanikab.gitanjali@mulearn.md
  profiles/nayanikab.gitanjali@mulearn.md
Labels: Approved

#649 Create devadathandr@mulearn.md
  profiles/devadathandr@mulearn.md
Labels: Changes Requested

#678 Create ArunVV@mulearn.md
  profiles/ArunVV@mulearn.md
Labels: Approved

#687 Create ashwinkrishnam@mulearn.md
  profiles/ashwinkrishnam@mulearn.md
Labels: Approved

#703 Create fathimanoureenb@mulearn.md
  profiles/fathimanoureenb@mulearn.md
Labels: Approved

#699 Create rubyaj24@mulearn
  profiles/rubyaj24@mulearn
Labels: Approved

#700 Create joyaljoseph-2@mulearn.md
  joyaljoseph-2@mulearn.md
Labels: Approved

#702 Create anandukrishnavr@mulearn.md
  profiles/anandukrishnavr@mulearn.md
Labels: Approved

#708 Pull request completed
  profiles/nijinkvarghese@mulearn.md
Labels: Approved

#744 Create saranyasnair@mulearn.md
  profiles/saranyasnair@mulearn.md
Labels: Approved

#757 muhammadshafim@mulearn.md
  profiles/muhammadshafim@mulearn.md
Labels: Approved

#790 Create sreelakshmip-9@mulearn.md
  profiles/sreelakshmip-9@mulearn.md
Labels: Approved

#805 Create suryasudheer@mulearn.md
  profiles/suryasudheer@mulearn.md
Labels: Approved

#806 Create mohammedadil@mulearn.md
  profiles/mohammedadil@mulearn.md
Labels: Approved

#807 Create johnsraju@mulearn.md
  profiles/johnsraju@mulearn.md
Labels: Approved

#808 Add mariaanngeorge-1@mulearn.md
  profiles/mariaanngeorge-1@mulearn.md
Labels: Approved

#823 Create jyothilakshmi.v.pillai@mulearn
  profiles/jyothilakshmi.v.pillai@mulearn
Labels: Approved

#844 create revathyprasad@mulearn.md
  profiles/revathyprasad@mulearn.md
Labels: Approved

#847 Create akshain.v@mulearn.md
  profiles/akshain.v@mulearn.md
Labels: Approved

#851 Update abhisheka-3@mulearn.md
  profiles/abhisheka-3@mulearn.md
Labels: Approved

#852 Create mohammedsalah-1@mulearn.md
  profiles/mohammedsalah-1@mulearn.md
Labels: Approved

#854 Create BijulalP@mulearn.md
  profiles/BijulalP@mulearn.md
Labels: Approved

#857 Create harinands@mulearn.md
  profiles/harinands@mulearn.md
Labels: Approved

#861 Created Profile
  profiles/snithin@mulearn.md
Labels: Approved

#862 Update fidhaelaveettil@mulearn.md
  profiles/fidhaelaveettil@mulearn.md
Labels: Approved

#877 anupama@mulearn.md
  profiles/anupama@mulearn.md
Labels: Approved

#879 abhilashkv@mulearn.md
  profiles/abhilashkv@mulearn.md
Labels: Approved

#941 Create savadkn@mulearn.md
  profiles/savadkn@mulearn.md
Labels: Approved

#848 Create abhaychandran@mulearn.md
  profiles/abhaychandran@mulearn.mt
Labels: Changes Requested

#973 Create sahalks@mulearn.md
  profiles/sahalks@mulearn.md
Labels: good first issue, Approved, valid

#981 Revert "anwarsadathky@mulearn"
  anwarsadathky@mulearn.md
Labels: Invalid request, help wanted, Changes Requested
