Repository gtech-mulearn/IEEE-LAUNCHPAD, pull requests merged in 2024-07, with the labels that each got.

#993 anwarsadathky@mulearn
  profiles/anwarsadathky@mulearn.md
Labels: Approved

#983 Portfolio Readme
  profiles/sreelakshmianilkumar@mulearn.md
Labels: Approved

#994 Create akshaysrajan@mulearn.md
  profiles/akshaysrajan@mulearn.md
Labels: Approved

#723 Create abhishekkumar@mulearn
  profiles/abhishekkumar@mulearn.md
Labels: Approved

#997 Create gokulchandv@mulearn.md
  profiles/gokulchandv@mulearn.md
Labels: Changes Requested

#1020 Create manualgeorge@mulearn.md
  profiles/manualgeorge@mulearn.md
Labels: Approved

#1052 Create harithath@mulearn.md
  profiles/harithath@mulearn.md
Labels: Changes Requested

#1054 fathimanajiya@mulearn
  profiles/fathimanajiya@mulearn.md
Labels: Approved

#1053 Create liyamariyaabraham@mulearn.md
  profiles/liyamariyaabraham@mulearn.md
Labels: Changes Requested

#1115 Create Sameenakn@mulearn.md
  profiles/Sameenakn@mulearn.md
Labels: good first issue, Approved

#1132 Revert "Revert "Create aswinr-2@mulearn.md""
  profiles/aswinr-2@mulearn.md
Labels: Changes Requested

#1133 Revert "Create aswinr-2@mulearn.md"
  profiles/profiles/aswinr-2@mulearn.md
Labels: Changes Requested

#1139 saranskumar@mulearn
  profiles/saranskumar@mulearn.md
Labels: good first issue, Approved

#1136 Profile Creation
  profiles/soorajp@mulearn.md
Labels: good first issue, Approved

#1135 Create vishnusudheer@mulearn.md
  profiles/vishnusudheer@mulearn.md
Labels: good first issue, Approved

#1147 Create aravindp@mulearn.md
  profiles/aravindp@mulearn.md
Labels: Approved
